import os
import yaml

# from .llm_eval.single_role.faireval.calc_score_comparison.gpt_35_0301.output_parser import LLMEvalParser
# from .llm_eval.multi_role.only_static_assign.faireval.two_turns_sequential.two_different_role.calc_score_comparison.gpt_35_0301.output_parser import LLMEvalParser
# from .llm_eval.multi_role.only_static_assign.faireval.two_turns_concurrent.two_different_role.calc_score_comparison.gpt_35_0301.output_parser import LLMEvalParser
# from .llm_eval.multi_role.only_static_assign.faireval.two_turns_summary.two_different_role.calc_score_comparison.gpt_35_0301.output_parser import LLMEvalParser

# from .demo.science_team.output_parser import LLMEvalParser

from .llm_eval.output_parser import LLMEvalParser

# from .llm_eval.multi_role.only_static_assign.adversarial.two_turns_sequential.three_different_role.calc_score_comparison.gpt_35_0301.output_parser import LLMEvalParser
# from .llm_eval.multi_role.only_static_assign.adversarial.two_turns_sequential.three_different_role.calc_score_comparison.gpt_35_0613.output_parser import LLMEvalParser
# from .llm_eval.multi_role.only_static_assign.adversarial.two_turns_sequential.three_different_role.calc_score_comparison.gpt_4.output_parser import LLMEvalParser